### ISSUE TITLE
Errors while running rtc2jira

### ISSUE THREAD

**Issue by krunalramanuj** [rtcTo/rtc2jira#25]
2018-01-11 18:47:01:426 INFO  OrientDB Engine shutdown complete [Orient]
2018-01-11 18:47:01:426 INFO  OrientDB Server shutdown complete [OServer]Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: A message body reader for Java class to.rtc.rtc2jira.exporter.jira.entities.Project, and Java type class to.rtc.rtc2jira.exporter.jira.entities.Project, and MIME media type text/html; charset=UTF-8 was not found
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:630)
	at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
	at to.rtc.rtc2jira.exporter.jira.JiraRestAccess.get(JiraRestAccess.java:59)
	at to.rtc.rtc2jira.exporter.jira.JiraExporter.getProject(JiraExporter.java:447)
	at to.rtc.rtc2jira.exporter.jira.JiraExporter.initialize(JiraExporter.java:139)
	at to.rtc.rtc2jira.ExportManager.export(ExportManager.java:55)
	at to.rtc.rtc2jira.Main.main(Main.java:22)

**Comment by WtfJoke** [comment]
Did you run maven update?

**Comment by krunalramanuj** [comment]
Yes. I have run the maven update. After debugging the issue I found that in the response I am getting value "text/html"  for the field content-type of header. 

To get response in JSON format we are setting it using following code.
Builder responseBuilder =
        webResource.header("Authorization", "Basic " + authentification).type(MediaType.APPLICATION_JSON)
            .accept(MediaType.APPLICATION_JSON);

Looks like still the response is text/html. Could you please provide your suggestion on this.

**Comment by WtfJoke** [comment]
Were you able to solve it? @krunalramanuj
