### ISSUE TITLE
Error when running the main class

### ISSUE THREAD

**Issue by ybhavm** [rtcTo/rtc2jira#32]
Hi Team,
When i run my main class i am getting the following error. Please let me know if you can help me in resolving this..

2020-04-10 09:57:48:540 INFO  OrientDB Server shutdown complete [OServer]Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@da5d5e1; line: 1, column: 256977] (through reference chain: to.rtc.rtc2jira.exporter.jira.entities.IssueSearchResult["issues"]->to.rtc.rtc2jira.exporter.jira.entities.Issue["fields"]->to.rtc.rtc2jira.exporter.jira.entities.IssueFields["customfield_10008"])
       at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:644)
       at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:586)
       at to.rtc.rtc2jira.exporter.jira.entities.IssueSearch.run(IssueSearch.java:36)
       at to.rtc.rtc2jira.exporter.jira.JiraExporter.ensureWorkItemWithId(JiraExporter.java:168)
       at to.rtc.rtc2jira.exporter.jira.JiraExporter.createOrUpdateItem(JiraExporter.java:152)
       at to.rtc.rtc2jira.ExportManager.export(ExportManager.java:65)
       at to.rtc.rtc2jira.Main.main(Main.java:22)
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@da5d5e1; line: 1, column: 256977] (through reference chain: to.rtc.rtc2jira.exporter.jira.entities.IssueSearchResult["issues"]->to.rtc.rtc2jira.exporter.jira.entities.Issue["fields"]->to.rtc.rtc2jira.exporter.jira.entities.IssueFields["customfield_10008"])
       at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
       at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219)
       at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:44)
       at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:13)
       at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
       at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
       at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
       at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
       at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
       at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
       at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
       at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
       at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
       at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
       at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695)
       at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1308)
       at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
       at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
       ... 6 more

**Comment by WtfJoke** [comment]
Hi @ybhavm 

Try deleting the lines:
```
  @JsonView(IssueView.Update.class)
  @XmlElement(name = "customfield_10006")
  public String getEpicLink() { // done
    return epicLink;
  }

  public void setEpicLink(String epicLink) {
    this.epicLink = epicLink;
  }
```
in [IssueFields.java](https://github.com/rtcTo/rtc2jira/blob/master/src/main/java/to/rtc/rtc2jira/exporter/jira/entities/IssueFields.java) and let me know if it works (maybe you need to delete other customfields as well).
